import math
def sine(x):
    return math.sin(x)
def cosine(x):
    return math.cos(x)
def tangent(x):
    return math.tan(x)
def logarithm10(x):
    return math.log(x)
def logarithm2(x):
    return math.log2(x)
